package com.sachin.Java8.FunctionalProgramming.p01_Lambda_Expressions;

/**
 * Demonstrates the evolution of code optimization in Java 8.
 * <p>
 * This class contrasts the verbose, traditional object-oriented approach
 * of implementing interfaces against the clean, concise syntax of Lambda Expressions.
 * @author Sachin
 * @since 2026-06-19
 */
public class LeaveragingLambdas {

    /**
     * Execution entry point. Compares the traditional implementation class
     * approach against the modern Lambda expression approach.
     */
    static void main() {
        // 1. Legacy Approach: Verbose and time-consuming.
        // Requires creating an implementing class and manual instantiation
        // just for a single line of logic (a successor operation).
        SuccessorImpl successor = new SuccessorImpl();
        System.out.println(successor.operation(2)); // returns 3

        // 2. Java 8 Approach: Concise and efficient.
        // Uses a Lambda Expression to implement the functional interface inline,
        // eliminating the need for the SuccessorImpl class entirely.
        IMiniOperations successor2 = a -> a + 1;
        System.out.println(successor2.operation(2)); // output 3
    }
}

/**
 * A functional interface designed to handle isolated, single-purpose operations.
 * <p>
 * Because this interface contains exactly one abstract method, it is eligible
 * to be targeted by Lambda Expressions or Method References.
 */
interface IMiniOperations {

    /**
     * Performs a mathematical or logical operation on the given integer.
     *
     * @param a The input integer to be processed.
     * @return The resulting integer after applying the operation.
     */
    int operation(int a);
}

/**
 * A concrete implementation of {@link IMiniOperations} that increments the input by 1.
 * * @deprecated As of Java 8, this explicit class implementation is redundant.
 * Use inline Lambda expressions instead.
 */
@Deprecated
class SuccessorImpl implements IMiniOperations {

    /**
     * {@inheritDoc}
     * <p>
     * Returns the successor ($a + 1$) of the provided integer.
     */
    @Override
    public int operation(int a) {
        return a + 1;
    }
}

/**
 * {@Note: These notes are generated by me, else all the classes in this file are custom, dont get confuse by seeing the official like doc for them} */